# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
branches:
  only:
    - master
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod setup
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace Example/OKPaypp.xcworkspace -scheme OKPaypp-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --use-libraries --allow-warnings --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 3